export const CHANNELS = {
  TASK_GET_ALL: 'task:getAll',
  TASK_GET_BY_ID: 'task:getById',
  TASK_CREATE: 'task:create',
  TASK_UPDATE: 'task:update',
  TASK_DELETE: 'task:delete',

  TASK_SESSION_GET_ALL: 'taskSession:getAll',
  TASK_SESSION_GET_BY_ID: 'taskSession:getById',
  TASK_SESSION_GET_BY_TASK_ID: 'taskSession:getByTaskId',
  TASK_SESSION_CREATE: 'taskSession:create',
  TASK_SESSION_UPDATE: 'taskSession:update',
  TASK_SESSION_DELETE: 'taskSession:delete',
  TASK_SESSION_CLOSE_OPEN_BY_TASK_ID: 'taskSession:closeOpenByTaskId',

  TIME_ENTRY_GET_ALL: 'timeEntry:getAll',
  TIME_ENTRY_GET_BY_ID: 'timeEntry:getById',
  TIME_ENTRY_GET_BY_TASK_ID: 'timeEntry:getByTaskId',
  TIME_ENTRY_CREATE: 'timeEntry:create',
  TIME_ENTRY_UPDATE: 'timeEntry:update',
  TIME_ENTRY_DELETE: 'timeEntry:delete',

  SETTINGS_GET: 'settings:get',
  SETTINGS_SET: 'settings:set',
  SETTINGS_GET_ALL: 'settings:getAll',
  SETTINGS_DELETE: 'settings:delete',

  REPORT_GET_TIME_ENTRIES_IN_RANGE: 'report:getTimeEntriesInRange',

  APP_GET_RECOVERY_INFO: 'app:getRecoveryInfo',
} as const

export type IpcChannelName = (typeof CHANNELS)[keyof typeof CHANNELS]

export const IPC_CHANNELS: readonly IpcChannelName[] = Object.values(CHANNELS)

export const TASK_GET_ALL = CHANNELS.TASK_GET_ALL
export const TASK_GET_BY_ID = CHANNELS.TASK_GET_BY_ID
export const TASK_CREATE = CHANNELS.TASK_CREATE
export const TASK_UPDATE = CHANNELS.TASK_UPDATE
export const TASK_DELETE = CHANNELS.TASK_DELETE
export const TASK_SESSION_GET_ALL = CHANNELS.TASK_SESSION_GET_ALL
export const TASK_SESSION_GET_BY_ID = CHANNELS.TASK_SESSION_GET_BY_ID
export const TASK_SESSION_GET_BY_TASK_ID = CHANNELS.TASK_SESSION_GET_BY_TASK_ID
export const TASK_SESSION_CREATE = CHANNELS.TASK_SESSION_CREATE
export const TASK_SESSION_UPDATE = CHANNELS.TASK_SESSION_UPDATE
export const TASK_SESSION_DELETE = CHANNELS.TASK_SESSION_DELETE
export const TASK_SESSION_CLOSE_OPEN_BY_TASK_ID =
  CHANNELS.TASK_SESSION_CLOSE_OPEN_BY_TASK_ID
export const TIME_ENTRY_GET_ALL = CHANNELS.TIME_ENTRY_GET_ALL
export const TIME_ENTRY_GET_BY_ID = CHANNELS.TIME_ENTRY_GET_BY_ID
export const TIME_ENTRY_GET_BY_TASK_ID = CHANNELS.TIME_ENTRY_GET_BY_TASK_ID
export const TIME_ENTRY_CREATE = CHANNELS.TIME_ENTRY_CREATE
export const TIME_ENTRY_UPDATE = CHANNELS.TIME_ENTRY_UPDATE
export const TIME_ENTRY_DELETE = CHANNELS.TIME_ENTRY_DELETE
export const SETTINGS_GET = CHANNELS.SETTINGS_GET
export const SETTINGS_SET = CHANNELS.SETTINGS_SET
export const SETTINGS_GET_ALL = CHANNELS.SETTINGS_GET_ALL
export const SETTINGS_DELETE = CHANNELS.SETTINGS_DELETE
export const REPORT_GET_TIME_ENTRIES_IN_RANGE =
  CHANNELS.REPORT_GET_TIME_ENTRIES_IN_RANGE
export const APP_GET_RECOVERY_INFO = CHANNELS.APP_GET_RECOVERY_INFO
